# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

os:
  - linux
  - osx

compiler:
  - gcc
  - clang
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.2
      - g++-4.2
      - gfortran-4.2