# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

warnings_are_errors: false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8